apiVersion: v1
kind: LimitRange
metadata:
  name: mysql-project-limits
  namespace: mysql-project
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      max:
        cpu: "2"
        memory: 2Gi