apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: mysql-project
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: local-demo-root-change-this
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress
  MYSQL_PASSWORD: local-demo-change-this